### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by JetseVerschuren** [oceanroleplay/discord.ts#1]
Hi, I just switched to your branch because OwenCalvin's slash branch is currently broken. Thanks for making your fork available via npm.

When registering a command with option I get a TypeError (see title), it's caused by this code:
```TypeScript
@Discord()
export abstract class Credits {
  @Slash("credits")
  credits(
    @SlashOption("x", { description: "x value" })
    x: number,
    interaction: CommandInteraction
  ): void {
    interaction.reply("credits response");
  }
}
```
The full stacktrace is:
```
TypeError: Cannot read property '0' of undefined
    at /home/jetse/projects/BetaClimbers/DiscordBot/node_modules/discordx/src/decorators/decorators/SlashOption.ts:26:72
    at /home/jetse/projects/BetaClimbers/DiscordBot/node_modules/tslib/tslib.js:104:41
    at DecorateProperty (/home/jetse/projects/BetaClimbers/DiscordBot/node_modules/reflect-metadata/Reflect.js:553:33)
    at Reflect.decorate (/home/jetse/projects/BetaClimbers/DiscordBot/node_modules/reflect-metadata/Reflect.js:123:24)
    at Object.__decorate (/home/jetse/projects/BetaClimbers/DiscordBot/node_modules/tslib/tslib.js:98:96)
    at /home/jetse/projects/BetaClimbers/DiscordBot/src/commands/Credits.ts:7:3
    at Object.<anonymous> (/home/jetse/projects/BetaClimbers/DiscordBot/src/commands/Credits.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/home/jetse/projects/BetaClimbers/DiscordBot/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-2853484122283596.js:69:33)
```

After looking at the source and some experimentation I found that manually specifying the type fixes the error. That works, but is less than ideal.

```TypeScript
@Discord()
export abstract class Credits {
  @Slash("credits")
  credits(
    @SlashOption("x", { description: "x value", type: "INTEGER" })
    x: number,
    interaction: CommandInteraction
  ): void {
    interaction.reply("credits response");
  }
}
```

With debugging I could verify that `Reflect.getMetadata("design:paramtypes", target, key)` returns `undefined`. I have no idea beyond that what the problem is (nor did I really investigate). If you need more information, just let me know.

**Comment by JetseVerschuren** [comment]
Nevermind, I found the problem: I didn't have `emitDecoratorMetadata` enabled in `tsconfig.json` :facepalm:. Should've read the docs more carefully.
